from sklearn.feature_extraction.text import TfidfVectorizer

doc1 = '''(CNN)North Korean leader Kim Jong Un received a "personal letter" from US President Donald Trump, according to North Korean state news agency KCNA.KCNA reported that Kim "said with satisfaction that the letter is of excellent content," after reading it."Kim Jong Un said that he would seriously contemplate the serious content" and appreciated the "extraordinary courage of President Trump," KCNA added.The White House did not immediately respond to a request for comment.South Korea\'s Office of the President "evaluates the exchanges of personal letters between the leaders of the United States and North Korea positively from the perspective of continuing the momentum of the US-North Korea talks," according to a statement it released Saturday. This is not the first mysterious letter to be exchanged between the leaders. Earlier this month, Trump told reporters about a "beautiful letter" he received from Kim, the first since the February summit in Hanoi that saw both leaders leave empty-handed."I appreciated the letter," Trump said at the time. He did not reveal the contents of the letter.But the letter lacked substance and did not contain any details on a way forward for the stalled denuclearization talks between the two countries, according to a source familiar with its contents. An administration official described the letter as a "birthday greeting." Trump\'s birthday was that week and the official says Kim wished the President good health.'''
doc2 = '''New York (CNN)Fox News hosts Chris Wallace and Shep Smith challenged President Donald Trump\'s comments about when and why he decided to call off a strike against Iran.Trump said Friday that the military was "cocked and loaded" to fire on Iran in retaliation for shooting down a US drone earlier this week. But he reversed course "10 minutes before the strike" when he learned 150 people could die in the attack, the president said in a series of tweets.Smith said Fox News\' reporting found that Trump would have been given a casualty estimate at a briefing hours before that."Something\'s wrong there," Smith said about the president\'s comments.Wallace also had questions. "I talked to a former top national security official in an earlier Republican administration who says this just doesn\'t add up," Wallace said during a midday segment Friday. "The timeline for when he learned information and when he decided to act doesn\'t make a lot of sense," Wallace told Shep during the Fox News segment. "Maybe that\'s the biggest problem. You could argue: if you don\'t want to strike, don\'t strike. If you want to strike, do strike — but don\'t send mixed messages that confuse not only your enemies, but even your allies and people here in this country."Smith then questioned Trump\'s decision to "tweet out the whole thought process of American foreign policy and intervention.""That\'s an observation," he added. "Not a critique."Trump has a cozy relationship with Fox News. He\'s hired a number of former employees from the network to posts within his administration.The president also reportedly corresponds directly with Fox News hosts like Tucker Carlson and Sean Hannity, conservative firebrands who currently host evening programs that routinely praise the president.Smith, who hosts daytime news coverage, and Wallace, the anchor of Fox News Sunday, have stood apart from Fox\'s opinion-oriented colleagues. Smith and Wallace have previously questioned or criticized actions by Trump or his administration.'''
doc3 = "An apple a day keeps the doctor away"
doc4 = "Never compare an apple to an orange"
doc5 = "Never compare an apple to an orange"

documents = [doc1, doc2, doc3, doc4, doc5]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)
print(vectorizer.get_feature_names())
print(X.toarray())

pairwise_sim = X * X.T
print(pairwise_sim.A)
